name: generate-snake

on:
  schedule: # setiap 12 jam update otomatis
    - cron: "0 */12 * * *"
  workflow_dispatch: # bisa run manual lewat tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: zyalwfie
          outputs: dist/snake.svg

      - name: Push Snake to Output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
